# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021 Intel Corporation.

obj-$(CONFIG_VIDEO_HM11B1) += hm11b1.o
obj-$(CONFIG_VIDEO_GC5035) += gc5035.o
obj-$(CONFIG_VIDEO_OV01A1S) += ov01a1s.o
obj-$(CONFIG_VIDEO_OV01A10) += ov01a10.o
obj-$(CONFIG_VIDEO_OV02C10) += ov02c10.o
obj-$(CONFIG_VIDEO_OV02E10) += ov02e10.o
obj-$(CONFIG_VIDEO_OV05C10) += ov05c10.o
obj-$(CONFIG_VIDEO_OV2740) += ov2740.o
obj-$(CONFIG_VIDEO_HM2170) += hm2170.o
obj-$(CONFIG_VIDEO_HM2170) += hm2172.o
obj-$(CONFIG_VIDEO_HI556) += hi556.o
obj-$(CONFIG_VIDEO_AR0234) += ar0234.o
obj-$(CONFIG_VIDEO_LT6911UXC) += lt6911uxc.o
obj-$(CONFIG_VIDEO_LT6911UXE) += lt6911uxe.o
#obj-$(CONFIG_VIDEO_D4XX) += d4xx.o
#obj-$(CONFIG_VIDEO_IMX390) += imx390.o
obj-$(CONFIG_VIDEO_IMX477) += imx477.o
obj-$(CONFIG_POWER_CTRL_LOGIC) += power_ctrl_logic.o
